import objects.regulatorObjects as r

r.rConfig.start()

while r.config["filled"] is False:
       print("Loading Configurations")  
r.rEc.start()
r.rHumWater.start()
r.rLight.start()
r.rMist.start()
r.rMold.start()
r.rNutrition.start()
r.rPH.start()
r.rPHDown.start()
r.rPHUp.start()
r.rRootHum.start()
r.rRootPres.start()
r.rRootTemp.start()
r.rShootHum.start()
r.rShootPres.start()
r.rShootTemp.start()
r.rWaterLevel.start()
r.rUpload.start()

r.rConfig.join()
r.rEc.join()
r.rHumWater.join()
r.rLight.join()
r.rMist.join()
r.rMold.join()
r.rNutrition.join()
r.rPH.join()
r.rPHDown.join()
r.rPHUp.join()
r.rRootHum.join()
r.rRootPres.join()
r.rShootHum.join()
r.rShootPres.join()
r.rShootTemp.join()
r.rWaterLevel.join()
r.rUpload.join()
